[package]
name = "impatience"
version = "1.0.0"
edition = "2024"
authors = ["foax <a@fo.ax>"]
description = "A library for instrumentation of event-to-event latency over a network"
license = "GPL-3.0-ONLY"
repository = "https://github.com/xfoa/Impatience"
keywords = ["time", "sync", "udp", "network", "clock"]
categories = ["network-programming", "date-and-time", "development-tools::profiling"]
rust-version = "1.95"

[lib]
name = "impatience"
path = "src/lib.rs"

[[bin]]
name = "impatience"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.29"
libc = "0.2"
paste = "1.0.15"
rand = "0.10.1"
rkyv = "0.8"
seq-macro = "0.3.6"
serde = { version = "1", features = ["derive"], optional = true }
serde_json = "1"
statrs = { version = "0.18", optional = true }

[features]
default = ["serde"]
serde = ["dep:serde"]
uncertainty = ["dep:statrs"]
